// packages/vue/src/components/Field.vue
<template>
  <div v-if="!state.visible || !state.display"></div>
  <div v-else-if="$scopedSlots.default">
    <slot
      :form="form"
      :state="state"
      :props="innerProps"
      :mutators="mutators"
    ></slot>
  </div>
  <div v-else>
    <slot></slot>
  </div>
</template>

<script lang="ts">
import { defineComponent, provide } from '@vue/composition-api'
import { useField } from '../hooks/useField'
import { FieldSymbol } from '../constants'

export default defineComponent({
  name: 'VueInternalField',
  props: {
    path: {
      type: String,
      default: ''
    },
    triggerType: {
      type: String,
      default: 'onChange'
    }
  },
  setup(props) {
    const { state, field, props: innerProps, mutators, form } = useField(props)

    provide(FieldSymbol, field)

    return {
      state,
      innerProps,
      form,
      mutators
    }
  }
})
</script>

// packages/react/src/components/Field.tsx
import React from 'react'
import { useField } from '../hooks/useField'
import { isFn } from '@formily/shared'
import { IFieldStateUIProps } from '../types'
import { FieldContext } from '../context'

export const Field: React.FC<IFieldStateUIProps> = props => {
  const { state, field, props: innerProps, mutators, form } = useField(props)

  if (!state.visible || !state.display) return <React.Fragment />
  if (isFn(props.children)) {
    return (
      <FieldContext.Provider value={field}>
        {props.children({
          form,
          state,
          props: innerProps,
          mutators
        })}
      </FieldContext.Provider>
    )
  } else {
    return (
      <FieldContext.Provider value={field}>
        {props.children}
      </FieldContext.Provider>
    )
  }
}

Field.displayName = 'ReactInternalField'

Field.defaultProps = {
  path: '',
  triggerType: 'onChange'
}
