// packages/vue/src/components/Layout.vue
<template>
  <div>
    <slot v-bind="childProps"></slot>
  </div>
</template>

<script lang="ts">
import { defineComponent, provide } from '@vue/composition-api'
import { LayoutSymbol } from '../constants'
import { ILayoutProps } from '../types'
import { useLayout } from '../hooks/useLayout'

export default defineComponent({
  props: {
    /* eslint-disable vue/require-prop-types  */
    /* eslint-disable vue/require-default-prop */
    hasBorder: Boolean,
    context: {},
    isRoot: Boolean,
    isLayout: Boolean,
    defaultSettings: {},
    children: {},
    full: Boolean,
    layoutProps: {},
    className: String,
    label: {},
    required: Boolean,
    labelAlign: String,
    inline: Boolean,
    inset: Boolean,
    autoRow: Boolean,
    columns: Number,
    flex: Boolean,
    enableSafeWidth: Boolean,
    labelWidth: [Number, String],
    wrapperWidth: [Number, String],
    labelCol: Number,
    wrapperCol: Number,
    addonBefore: {},
    addonAfter: {},
    description: {},
    gutter: [Number, String],
    span: Number,
    grid: Boolean,
    contextColumns: Number,
    contextResponsive: Object,
    responsive: Object,
    size: String
  },
  setup({
    required,
    label,
    addonBefore,
    addonAfter,
    description,
    ...props
  }: ILayoutProps) {
    const layout = useLayout({ ...props, isLayout: true })
    provide(LayoutSymbol, layout)
    const childProps = {
      ...layout,
      label,
      required,
      addonBefore,
      addonAfter,
      description
    }
    return {
      childProps
    }
  }
})
</script>

// packages/react/src/components/Layout.tsx
import React from 'react'
import { ILayoutProps } from '../types'
import { LayoutContext } from '../context'
import { useLayout, useLayoutItem } from '../hooks/useLayout'

// case1: form -> layout(inline/lablCol/wrappreCol)
// case2: layout -> layout
// case3: layout -> nested formitem
// case4: layout -> array nested formitem
export const Layout: React.FC<ILayoutProps> = ({
  children,
  required, label, addonBefore, addonAfter, description,
  ...props
}) => {
  const layout = useLayout({ ...props, isLayout: true })
  return <LayoutContext.Provider value={layout}>
    {children({
      ...layout,
      label,
      required,
      addonBefore,
      addonAfter,
      description,
    })}
  </LayoutContext.Provider>
}

// 1. labelAlign
// 2. inset
// 3. full
// 4. labelWidth/wrapperWidth
// 5. labelCol/wrapperCol
const Item = ({ children, ...props }) => {
  const layoutItem = useLayoutItem(props)
  return children(layoutItem)
}

Object.assign(Layout, {
  Item,
})

export default Layout
