// packages/react/src/components/FormProvider.tsx
import React from 'react'
import { useAttach } from '../hooks/useAttach'
import { FormContext } from '../shared'
import { IProviderProps } from '../types'

export const FormProvider: React.FC<IProviderProps> = props => {
  const form = useAttach(props.form)
  return (
    <FormContext.Provider value={form}>{props.children}</FormContext.Provider>
  )
}

FormProvider.displayName = 'FormProvider'

// packages/vue/src/components/FormProvider.vue
<template>
  <div>
    <slot></slot>
  </div>
</template>

<script lang="ts">
import { defineComponent, provide } from '@vue/composition-api'
import { FormSymbol } from '../shared'
import { IProviderProps } from '../types'
import { useAttach } from '../hooks/useAttach'

export default defineComponent({
  name: 'FormProvider',
  props: {
    form: {
      type: Object,
      required: true
    }
  },
  setup(props: IProviderProps) {
    useAttach(props.form)
    provide(FormSymbol, props.form)
  }
})
</script>
