// packages/react/src/components/ObjectField.tsx
import React from 'react'
import { useForm, useField } from '../hooks'
import { useAttach } from '../hooks/useAttach'
import { ReactiveField } from './ReactiveField'
import { FieldContext } from '../shared'
import { JSXComponent, IFieldProps } from '../types'

export const ObjectField = <D extends JSXComponent, C extends JSXComponent>(
  props: IFieldProps<D, C, Formily.Core.Models.ObjectField>
) => {
  const form = useForm()
  const parent = useField()
  const field = useAttach(
    form.createObjectField({ basePath: parent?.address, ...props })
  )

  return (
    <FieldContext.Provider value={field}>
      <ReactiveField field={field}>{props.children}</ReactiveField>
    </FieldContext.Provider>
  )
}

ObjectField.displayName = 'ObjectField'

// packages/vue/src/components/ObjectField.vue
<template>
  <ReactiveField :field="field">
    <slot :field="field" :form="field.form"></slot>
  </ReactiveField>
</template>

<script lang="ts">
import { provide } from '@vue/composition-api'
import { useField, useForm } from '../hooks'
import { useAttach } from '../hooks/useAttach'
import { FieldSymbol } from '../shared'
import { VueComponent, IFieldProps } from '../types'
import ReactiveField from './ReactiveField.vue'
import { defineObservableComponent } from '../utils/define-observable-component'

export default defineObservableComponent({
  name: 'ObjectField',
  components: { ReactiveField },
  /* eslint-disable vue/require-prop-types  */
  /* eslint-disable vue/require-default-prop */
  props: {
    name: {},
    title: {},
    description: {},
    value: {},
    initialValue: {},
    basePath: {},
    decorator: Array,
    component: Array,
    required: Boolean,
    display: String,
    pattern: String,
    validateFirst: Boolean,
    validator: {},
    reactions: Array
  },
  observableSetup<D extends VueComponent, C extends VueComponent>(
    collect,
    props: IFieldProps<D, C>
  ) {
    const form = useForm()
    const parent = useField()
    const basePath = props.basePath ? props.basePath : parent?.address
    const field = useAttach(
      form.createObjectField({
        ...props,
        basePath
      })
    )
    provide(FieldSymbol, field)

    return collect({
      field
    })
  }
})
</script>
