// packages/react/src/components/VirtualField.tsx
import React from 'react'
import { useVirtualField } from '../hooks/useVirtualField'
import { isFn } from '@formily/shared'
import { IVirtualFieldStateUIProps } from '../types'
import { FieldContext } from '../context'

export const VirtualField: React.FunctionComponent<IVirtualFieldStateUIProps> = props => {
  const { state, field, props: innerProps, form } = useVirtualField(props)
  if (!state.visible || !state.display) return <React.Fragment />
  if (isFn(props.children)) {
    return (
      <FieldContext.Provider value={field}>
        {props.children({
          form,
          state,
          props: innerProps
        })}
      </FieldContext.Provider>
    )
  } else {
    return (
      <FieldContext.Provider value={field}>
        {props.children}
      </FieldContext.Provider>
    )
  }
}

VirtualField.displayName = 'ReactInternalVirtualField'

VirtualField.defaultProps = {
  path: ''
}

// packages/vue/src/components/VirtualField.vue
<template>
  <div v-if="!state.visible || !state.display"></div>
  <div v-else-if="$scopedSlots.default">
    <slot :form="form" :state="state" :props="innerProps"></slot>
  </div>
  <div v-else>
    <slot></slot>
  </div>
</template>

<script lang="ts">
import { defineComponent, provide } from '@vue/composition-api'
import { FieldSymbol } from '../constants'
import { useVirtualField } from '../hooks/useVirtualField'

export default defineComponent({
  name: 'VueInternalVirtualField',
  props: {
    path: {
      type: String,
      default: ''
    }
  },
  setup(props) {
    const { state, field, props: innerProps, form } = useVirtualField(props)
    provide(FieldSymbol, field)

    return {
      state,
      innerProps,
      form
    }
  }
})
</script>
